services:
  db:
    image: postgres:15-alpine
    container_name: aberdeenshireplanthire-co-uk-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: planthire
      POSTGRES_PASSWORD: Planthire367%2B%3F
      POSTGRES_DB: planthire
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - webnet

  app:
    build: .
    container_name: aberdeenshireplanthire-co-uk
    restart: always
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=aberdeenshireplanthire.co.uk
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=aberdeenshireplanthire.co.uk
      - LETSENCRYPT_EMAIL=umbrelladigitals@gmail.com
    depends_on:
      - db
    networks:
      - webnet

networks:
  webnet:
    external: true

volumes:
  db_data:
